account/urls.py
from django.urls import path
from . import views

# app_name = 'account'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('request_reset_password/', views.request_reset_password, name='request_reset_password'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('change_password', views.change_password, name='change_password'),
    path('logout/', views.logout, name='logout'),
    path('delete_account/', views.delete_account, name='delete_account'),
]

dashboard/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('books/', views.books, name='books'),
    path('magazines', views.magazines, name='magazines'),
    path('my_loans/', views.my_loans, name='my_loans'),
    path('expired_loans/', views.expired_loans, name='expired_loans'),
]

loan/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('new_loan/', views.new_loan, name='new_loan'),
    path('return_loan/', views.return_loan, name='return_loan'),
]

account/models.py
from django.db import models
from django.contrib.auth.models import User
from secrets import token_urlsafe

class PasswordResetRequest(models.Model):
    email = models.CharField(max_length=100)
    token = models.CharField(max_length=43, default=token_urlsafe)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f'Active: {self.active} // {self.token}'

account/views.py
from django.shortcuts import render, reverse
from django.contrib.auth import authenticate, login as login_method, logout as logout_method
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from . models import PasswordResetRequest

def login(req):

    if req.user.is_authenticated: ### Check if user is already logged in
        return HttpResponseRedirect(reverse('dashboard:dashboard'))

    context = {}
    if req.method == 'POST':
        username = req.POST['login-username']
        password = req.POST['login-password']

        user = authenticate(req, username=username, password=password)

        if user:
            login_method(req, user)
            return HttpResponseRedirect(reverse('dashboard:dashboard'))
        else:
            context = {
                'message': 'Username or password are incorrect.'
            }
            
    return render(req, 'login.html', context)

def logout(req):
    logout_method(req)
    return render(req, 'login.html')

def signup(req):

    if req.user.is_authenticated: ### Check if user is already logged in
        return HttpResponseRedirect(reverse('dashboard:dashboard'))

    context = {}
    if req.method == 'POST':

        ### Input values
        firstname = req.POST['first_name']
        lastname = req.POST['last_name']
        username = req.POST['username']
        email = req.POST['email']
        password1 = req.POST['password']
        password2 = req.POST['password_confirm']

        ### Staff registration
        is_staff = req.POST['is_staff']
        staff_token = req.POST['staff_token']
        staff_registration_token = 'zxcvbnm'

        if password1 == password2: ### Check if passwords match
            if User.objects.filter(username=username).exists(): ### Check if user already exists
                context = {
                    'message': 'User already exists'
                }
            else:
                if is_staff == 'staff': ### Check if new user is staff 
                    if staff_token == staff_registration_token: ### Check if staff registration token is correct
                        User.objects.create_superuser(
                            username, email, password1, first_name=firstname, last_name=lastname
                        )
                        context = {
                            'message': 'Staff user has been created! You can now login and access /admin.'
                        }
                    else:
                        context = {
                            'message': 'Staff token was not correct'
                        }
                else:
                    User.objects.create_user(
                        username, email, password1, first_name=firstname, last_name=lastname
                    )
                    context = {
                        'message': 'User has been created! You can now go you the login page and login.'
                    }
        else:
            context = {
                'message': 'Passwords did not match.'
            }
    return render(req, 'signup.html', context)

def request_reset_password(req):
    context = {}
    if req.method == 'POST':
        email = req.POST['reset-email']
        is_email_valid = User.objects.filter(email=email).exists()

        if is_email_valid: ### Check if email exists in our system
            new_request = PasswordResetRequest()
            new_request.email = email
            new_request.save()
            print(new_request) ### This is what should be sent to the users email
            return HttpResponseRedirect(reverse('password_reset'))

        else:
            context = {
                'message': 'The email does not exists in our system'
            }


    return render(req, 'request_reset_password.html', context)

def password_reset(req):
    context = {}

    if req.method == 'POST':
        token = req.POST['pass-reset-token']
        email = req.POST['pass-reset-email']
        password = req.POST['pass-reset-password']
        password_confirm = req.POST['pass-reset-password-confirm']

        if password == password_confirm: ### Check if passwords match
            valid_token = PasswordResetRequest.objects.filter(token=token, active=True).exists()
            valid_user = User.objects.filter(email=email).exists()

            if valid_token and valid_user: ### Check if token exists and is active
                db_token = PasswordResetRequest.objects.get(token=token)
                db_token.active = False
                db_token.save()

                user = User.objects.get(email=email)
                user.set_password(password)
                user.save()

                context = {
                    'success_message': f'Your password has succesfully been changed! Go back to the login page',
                    'message': False
                }
            else:
                context = {
                    'message': 'Invalid token or email.'
                }
        else:
            context = {
                'message': 'Passwords do not match.'
            }

    return render(req, 'password_reset.html', context)

def change_password(req):
    context = {}

    if req.method == 'POST':
        username = req.user.get_username()
        current_password = req.POST['change-current-password']
        new_password = req.POST['change-new-password']
        new_password_confirm = req.POST['change-new-password-confirm']

        if new_password == new_password_confirm: ### Check if new passwords match
            valid_user = authenticate(req, username=username, password=current_password)
            if valid_user: ### Check if current password is correct
                user = User.objects.get(username=username)
                user.set_password(new_password)
                user.save()
                context = {
                    'message': 'Your password has been updated!'
                }
            else:
                context = {
                    'message': 'Current password is wrong.'
                }
        else:
            context = {
                'message': 'Your new password do not match.'
            }

    return render(req, 'change_password.html', context)

def delete_account(req):
    context = {}
    if req.method == 'POST':
        username = req.user.get_username()
        password = req.POST['delete-password']
        text_delete = req.POST['delete-confirm']
        valid_user = authenticate(req, username=username, password=password)
        if valid_user: ### Check if password is correct
            if text_delete == 'delete':
                logout_method(req)
                user = User.objects.get(username=username)
                user.delete()
                return HttpResponseRedirect(reverse('login'))
            else:
                context = {
                    'message': '\'delete\' was not typed correctly.'
                }
        else:
            context = {
                'message': 'Wrong password.'
            }

    return render(req, 'delete_account.html', context)
    

account/templates/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <title>Document</title>
</head>
<body>

    {% if user.is_authenticated %}
        {% if user.is_staff %}
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'dashboard:dashboard' %}">Welcome {{ user }}!</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:dashboard' %}">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:my_loans' %}">My loans</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:expired_loans' %}">Expired loans</a>
                </li>
                </ul>
            </div>
            </nav>
            <a href="{% url 'publish_material' %}"><button type="button" class="btn btn-success m-2">+ Publish books/magazines</button></a>
            <a href="{% url 'register_material' %}"><button type="button" class="btn btn-info m-2">Register material to system</button></a>
        {% else %}
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'dashboard:dashboard' %}">Welcome {{ user }}!</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:dashboard' %}">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:my_loans' %}">My loans</a>
                </li>
                </ul>
            </div>
            </nav>
        {% endif %}
    {% endif %}

    {% block content %}



    {% endblock %}

    {% if user.is_authenticated %}
        <div class=" p-2 py-5 d-flex jumbotron align-items-center">
            <div>
                <a class="text-white nounderline" href="{% url 'logout' %}"><button class="btn btn-danger">LOG OUT</button></a>
            </div>
            <div class="mx-5">
                <a href="{% url 'change_password' %}">Change password</a>
            </div>
            <div>
                <a href="{% url 'delete_account' %}">Delete account</a>
            </div>
        </div>
    {% endif %}

    <script src="{% static 'js/app.js' %}"></script>
</body>
</html>

account/templates/change_password.html
{% extends './_base.html' %}

{% block content %}

    <div class="m-2">

        <h1><b>Change password</b></h1>

        <a href="{% url 'dashboard:dashboard' %}">&#8592; Back to dashboard</a>

        <br />
        <br />
        <br />

        <form action="{% url 'change_password' %}" method="POST">
            {% csrf_token %}
            <div class="input-pair">
                <label for="change-current-password">Type current password</label>
                <input type="password" name="change-current-password" id="change-current-password" />
            </div>
            <div class="input-pair">
                <label for="change-new-password">Type new password</label>
                <input type="password" name="change-new-password" id="change-new-password" />
            </div>
            <div class="input-pair">
                <label for="change-new-password-confirm">Confirm new password</label>
                <input type="password" name="change-new-password-confirm" id="change-new-password-confirm" />
            </div>
            <br />
            <button class="btn btn-primary">CHANGE PASSWORD</button>
        </form>

        {% if message %}
            <p>{{ message }}</p>
        {% endif %}

    </div>

{% endblock %}

account/templates/delete_account.html
{% extends './_base.html' %}

{% block content %}

    <div class="m-2">

        <h1><b>Delete account</b></h1>

        <a href="{% url 'dashboard:dashboard' %}">&#8592; Back to dashboard</a>

        <p>Are you sure you want to delete your user <i>{{ user }}</i>?</p>
        <p>Confirm by typing your password and '<b>delete</b>'</p>
        <form action="{% url 'delete_account' %}" method="POST">
            {% csrf_token %}
            <div class="input-pair">
                <label for="delete-password">Password</label>
                <input type="password" name="delete-password" id="delete-password" />
            </div>
            <div class="input-pair">
                <label for="delete-confirm">Type 'delete'</label>
                <input type="text" name="delete-confirm" id="delete-confirm" />
            </div>
            <br />
            <button class="btn btn-danger">DELETE USER</button>
        </form>

        {% if message %}
            <p>{{ message }}</p>
        {% endif %}

    </div>

{% endblock %}

account/templates/login.html
{% extends './_base.html' %}

{% block content %}

    <div class="m-2">

        <h1><b>Login page</b></h1>

        <p>Don't have an account? <a href="{% url 'signup' %}">Sign up</a></p>

        <form action="{% url 'login' %}" method="POST">
            {% csrf_token %}
            <div class="input-pair">
                <label for="login-username">Username</label>
                <input type="text" name="login-username" id="login-username" />
            </div>
            <div class="input-pair">
                <label for="login-password">Password</label>
                <input type="password" name="login-password" id="login-password" />
            </div>
            <br />
            <button class="btn btn-primary">LOGIN</button>
        </form>
        <br />
        <p>Forgot your password? <a href="{% url 'request_reset_password' %}">Reset your password</a></p>

        {% if message %}
            <p>{{ message }}</p>
        {% endif %}

    </div>

{% endblock %}

account/templates/password_reset.html
{% extends './_base.html' %}

{% block content %}

    <div class="m-2">

        <h1><b>Confirm token and new password</b></h1>

        <form action="" method="POST">
            {% csrf_token %}
            <div class="input-pair">
                <label for="pass-reset-token">Insert token</label>
                <input type="text" name="pass-reset-token" id="pass-reset-token" />
            </div>
            <div class="input-pair">
                <label for="pass-reset-email">Email</label>
                <input type="email" name="pass-reset-email" id="pass-reset-email" />
            </div>
            <div class="input-pair">
                <label for="pass-reset-password">New password</label>
                <input type="password" name="pass-reset-password" id="pass-reset-password" />
            </div>
            <div class="input-pair">
                <label for="pass-reset-password-confirm">Confirm new password</label>
                <input type="password" name="pass-reset-password-confirm" id="pass-reset-password-confirm" />
            </div>
            <br />
            <button class="btn btn-primary">CHANGE PASSWORD</button>
        </form>

        {% if message %}
            <p>{{ message }}</p>
        {% endif %}

        {% if success_message %}
            <p>{{ success_message }}</p>
            <a href="{% url 'login' %}">Login</a>
        {% endif %}

    </div>
    
{% endblock %}

account/templates/request_reset_password.html
{% extends './_base.html' %}

{% block content %}

    <div class="m-2">

        <h1><b>Reset password</b></h1>

        <p>Go back to login page <a href="{% url 'login' %}">Login</a></p>

        <form action="{% url 'request_reset_password' %}" method="POST">
            {% csrf_token %}
            <div class="input-pair">
                <label for="reset-email">Email</label>
                <input type="email" name="reset-email" id="reset-email" />
            </div>
            <br />
            <button class="btn btn-primary">REQUEST NEW PASSWORD</button>
        </form>

        {% if message %}
            <p>{{ message }}</p>
        {% endif %}

    </div>
    
{% endblock %}

account/templates/signup.html
{% extends './_base.html' %}

{% block content %}

    <div class="m-2">

        <h1><b>Signup page</b></h1>

        <p>Already have an account? <a href="{% url 'login' %}">Login</a></p>

        <form action="{% url 'signup' %}" method="POST">
            {% csrf_token %}
            <div class="input-pair">
                <label for="first_name">First name</label>
                <input type="text" name="first_name" id="first_name" />
            </div>
            <div class="input-pair">
                <label for="last_name">Last name</label>
                <input type="text" name="last_name" id="last_name" />
            </div>
            <div class="input-pair">
                <label for="email">E-mail</label>
                <input type="email" name="email" id="email" />
            </div>
            <div class="input-pair">
                <label for="username">Username</label>
                <input type="text" name="username" id="username" />
            </div>
            <div class="input-pair">
                <label for="password">Password</label>
                <input type="password" name="password" id="password" />
            </div>
            <div class="input-pair">
                <label for="password_confirm">Confirm password</label>
                <input type="password" name="password_confirm" id="password_confirm" />
            </div>
            <div class="select-pair">
                <label for="is_staff">Staff</label>
                <select id="is_staff" name="is_staff" onchange="checkIfStaff(event)">
                    <option value="customer" selected>No</option>
                    <option value="staff">Yes</option>
                </select>
            </div>
            <div class="select-pair hidden" id="secretField">
                <label for="staff_token">Insert secret staff token</label>
                <input type="text" name="staff_token" id="staff_token" />
            </div>
            <br />
            <button class="btn btn-primary">SIGN UP</button>
        </form>

        {% if message %}
            <p>{{ message }}</p>
        {% endif %}

    </div>

{% endblock %}