dashboard/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('books/', views.books, name='books'),
    path('magazines', views.magazines, name='magazines'),
    path('my_loans/', views.my_loans, name='my_loans'),
    path('expired_loans/', views.expired_loans, name='expired_loans'),
]

loan/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('new_loan/', views.new_loan, name='new_loan'),
    path('return_loan/', views.return_loan, name='return_loan'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from addmaterial.models import Publishmaterial
from loan.models import Loan
from datetime import timedelta
import datetime


@login_required(login_url='/account/login/')
def dashboard(req):

    book_count = Loan.objects.filter(user=req.user, book_id__material_id__material_type='book', is_returned=False).count()
    magazine_count = Loan.objects.filter(user=req.user, book_id__material_id__material_type='magazine', is_returned=False).count()

    context = {
        'materials': Publishmaterial.objects.all().order_by('material_id__title'),
        'book_count': book_count,
        'magazine_count': magazine_count,
        'type': 'books or magazines',
        'response': 'Books and magazines',
    }
    return render(req, 'dashboard.html', context)

@login_required(login_url='/account/login/')
def books(req):
    context = {
        # 'materials': Addmaterial.objects.filter(material_type='book').order_by('-quantity_available','title'),
        'materials': Publishmaterial.objects.filter(material_id__material_type='book').order_by('material_id__title'),
        'type': 'books',
        'response': 'Books',
    }
    return render(req, 'dashboard.html', context)

@login_required(login_url='/account/login/')
def magazines(req):
    context = {
        'materials': Publishmaterial.objects.filter(material_id__material_type='magazine').order_by('material_id__title'),
        'type': 'magazines',
        'response': 'Magazines'
    }
    return render(req, 'dashboard.html', context)

@login_required(login_url='/account/login/')
def my_loans(req):

    user_loans = Loan.objects.filter(user=req.user, is_returned=False)

    book_count = Loan.objects.filter(user=req.user, book_id__material_id__material_type='book', is_returned=False).count()
    magazine_count = Loan.objects.filter(user=req.user, book_id__material_id__material_type='magazine', is_returned=False).count()

    context = {
        'user_loans': user_loans,
        'book_count': book_count,
        'magazine_count': magazine_count,
    }
    return render(req, 'my_loans.html', context)

@login_required(login_url='/account/login/')
def expired_loans(req):
    current_date = datetime.datetime.now()

    expired_material = Loan.objects.filter(loan_return_datetime__lt=current_date, is_returned=False).order_by('loan_return_datetime')

    context = {
        'date': datetime.datetime.now(),
        'expired_materials': expired_material,
    }
    is_user_staff = req.user.is_staff
    if is_user_staff: ### Check if user is staff member
        pass
    else:
        return HttpResponseRedirect(reverse('dashboard:dashboard'))

    return render(req, 'expired_loans.html', context)

dashboard/templates/dashboard.html
{% extends './_base.html' %}

{% block content %}

    <div class="m-2">
        <h1><b>Dashboard</b></h1>
        <h4>{{ response }}</h4>
        {% if message %}
            <p>{{ message }}</p>
        {% endif %}
        <div class="mt-4">
            <a class="mx-1" href="{% url 'dashboard:dashboard' %}">All</a>
            <a class="mx-1" href="{% url 'dashboard:books' %}">Books</a>
            <a class="mx-1" href="{% url 'dashboard:magazines' %}">Magazines</a>
        </div>

        {% if materials %}
            <table class="table mt-3">
                <thead>
                    <tr>
                    <th scope="col"></th>
                    <th scope="col">Title</th>
                    <th scope="col">Author</th>
                    <th scope="col">Year</th>
                    <th scope="col">Language</th>
                    <th scope="col">Pages</th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for material in materials %}
                        {% if material.is_loaned %}
                            <tr class="disabled-tr" disabled>
                        {% else %}
                            <tr>
                        {% endif %}
                            {% if material.material_id.material_type == 'book' %}
                                {% if book_count == 10 %}
                                    <td class="maximum-reached text-center"><i class="fa fa-book text-white"></i></td>
                                {% else %}
                                    <td class="text-center"><i class="fa fa-book text-info"></i></td>
                                {% endif %}
                            {% else %}
                                {% if magazine_count == 3 %}
                                    <td class="maximum-reached text-center"><i class="fa fa-sticky-note text-white"></<i></td>
                                {% else %}
                                    <td class="text-center"><i class="fa fa-sticky-note text-info"></<i></td>
                                {% endif %}
                            {% endif %}
                            <td>{{ material.material_id.title }}</td>
                            <td>{{ material.material_id.author }}</td>
                            <td>{{ material.material_id.year }}</td>
                            <td>{{ material.material_id.language }}</td>
                            <td>{{ material.material_id.pages }}</td>
                            <form action="{% url 'new_loan' %}" method="POST">
                            {% csrf_token %}
                                <input type="hidden" value="{{ material.material_id.id }}" name="material_data" />
                                <input type="hidden" value="{{ material.id }}" name="material_id" />
                                <td><button class="btn btn-info"><i class="fa fa-plus"></i> Loan</button></td>
                            </form>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p class="mt-3">Sorry! There is no {{ type }} available.</p>
        {% endif %}
    </div>
    
{% endblock %}

dashboard/templates/expired_loans.html
{% extends './_base.html' %}

{% block content %}

    <div class="m-2">
        <h1><b>Expired loans <i class="text-danger fa fa-exclamation-triangle"></i></b></h1>
        <p>{{ date.date }}</p>

        {% if expired_materials %}
            <table class="table mt-3">
                <thead>
                    <tr>
                        <th></th>
                        <th scope="col">User</th>
                        <th scope="col">Should have returned on date</th>
                        <th scope="col">Title</th>
                        <th scope="col">Time expired</th>
                    </tr>
                </thead>
                <tbody>
                    {% for expired_material in expired_materials %}
                    <tr>
                        <td><i class="text-danger fa fa-exclamation-triangle"></i></td>
                        <td>{{ expired_material.user }}</td>
                        <td class="text-danger">{{ expired_material.loan_return_datetime.date }}</td>
                        <td>{{ expired_material.book_id.material_id.title }}</td>
                        <td class="text-danger">{{ expired_material.date_diff }} days</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>There is no expired loans at the moment.</p>
        {% endif %}
    </div>


    
{% endblock %}

dashboard/templates/my_loans.html
{% extends './_base.html' %}

{% block content %}

    <div class="m-2">
        <h1><b>My loans</b></h1>
        <h4>Books: {{ book_count }}</h4>
        <h4>Magazines: {{ magazine_count }}</h4>
        {% if user_loans %}
            <table class="table mt-3">
                <thead>
                    <tr>
                    <th scope="col"></th>
                    <th scope="col">Title</th>
                    <th scope="col">Author</th>
                    <th scope="col">Loaned on</th>
                    <th scope="col">Return no later than</th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for user_loan in user_loans %}
                        <tr>
                            {% if user_loan.book_id.material_id.material_type == 'book' %}
                                <td><i class="fa fa-book text-info"></i></td>
                            {% else %}
                                <td><i class="fa fa-sticky-note text-info"></<i></td>
                            {% endif %}
                            <td scope="row">{{ user_loan.book_id }}</td>
                            <td>{{ user_loan.book_id.material_id.author }}</td>
                            <td class="text-success">{{ user_loan.loan_datetime }}</td>
                            <td class="text-danger"><b>{{ user_loan.loan_return_datetime }}</b></td>
                            <form action="{% url 'return_loan' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" value="{{ user_loan.id }}" name="loan_id">
                            <td><button class="btn btn-info"><i class="fa fa-undo"></i> Return</button></td>
                            </form>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p class="mt-3">You have no loans at the moment.</p>
        {% endif %}
    </div>
    
{% endblock %}